language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
      env: R_CODECOV=true
    - os: osx
      brew_packages: cairo
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true # Simulates CRAN builder, don't remove

addons:
  apt:
    packages: libcairo2-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

# Prevents Travis timeout for building stuff
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
